### ISSUE TITLE
Adding and Removing reactions hits guild ratelimits 

### ISSUE THREAD

**Issue by DarylJG94** [saanuregh/discord.js-pagination#23]
The way the module currently works with adding the reactions directly after reachother and the instant removal of reactions causes the bot to hit discords ratelimits incredibly quick, as a little hack workaround I have made the following changes: 

`	setTimeout(async()=>{
		await curPage.react(emojiList[0]);
	},1000);`

`	setTimeout(async()=>{
		await curPage.react(emojiList[1]);
	},3000);`

instead of the forloop, and the removal of reactions: 

`   setTimeout(async ()=> {
     reaction.users.remove(msg.author);
   },2000)`

**Comment by xMyThoLoGyx** [comment]
Where would you make those changes? Sorry :/ is it in the node module or in your code?

**Comment by psibean** [comment]
Are you positive it's the bot hitting a rate limit and not the user?

discord.js should be handling rate limits already, check it's [request handler](https://github.com/discordjs/discord.js/blob/0d68ca8eb9abdb517acee562fe01374416d225ed/src/rest/RequestHandler.js)

**Comment by DarylJG94** [comment]
My apologies for the short delay, it is indeed hitting rate limits when posting the initial reactions. I will provide a pull request shortly

**Comment by DarylJG94** [comment]
See Pullrequest  https://github.com/saanuregh/discord.js-pagination/pull/24

**Comment by psibean** [comment]
> My apologies for the short delay, it is indeed hitting rate limits when posting the initial reactions. I will provide a pull request shortly

How many reactions did you have? Was this across multiple servers at a time? The [global rate limit is 50 requests per second](https://discord.com/developers/docs/topics/rate-limits#:~:text=global%22%3A%20true%20%7D-,Global%20Rate%20Limit,per%20second%20during%20normal%20operations.) and there's no mention of an individual limit on the [create reaction endpoint](https://discord.com/developers/docs/resources/channel#create-reaction) - so I'm struggling to see how you're getting 50 reacts just on the INITIAL reactions.

Are you able to provide a minimal repository and the use case that replicates this?

Edit: if this is actually an issue, I'm not sure a hard coded timeout is the way to fix it. The exceptions (if any) should be exposed to the user for handling. Any timeouts should be configurable, and I'd like to have such changes incorporated into my PR which significantly restructures this module.
